/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import entity.HoaDon1.HoaDon;
import entity.HoaDon1.HoaDonChiTiet;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.HoaDon.HoaDonChiTietService;
import service.HoaDon.HoaDonService;

/**
 *
 * @author ADMIN
 */
public class HoaDonJPanel extends javax.swing.JPanel {

    private List<HoaDon> listHD = new ArrayList<>();
    private List<HoaDonChiTiet> listCT = new ArrayList<>();
    private DefaultTableModel defaultTableModel = new DefaultTableModel();
    private DefaultTableModel defaultTableModelHDCT = new DefaultTableModel();
    private HoaDonService hdService = new HoaDonService();
    private HoaDonChiTietService hdctService = new HoaDonChiTietService();
    private HoaDonChiTiet hdct = new HoaDonChiTiet();
    private HoaDon hd = new HoaDon();
    private int index = -1;

    /**
     * Creates
     */
    public HoaDonJPanel() {

        initComponents();
        filltableHD();
        //filltableHDCT();
    }

    

    public void filltableHD() {

        listHD = hdService.getallHD();
        defaultTableModel = (DefaultTableModel) tblHD.getModel();
        defaultTableModel.setRowCount(0);
        for (HoaDon hd : listHD) {
            defaultTableModel.addRow(hd.toDatata());
        }

    }

    public void filltableHDCT() {
        listCT = hdctService.getallHDCT();
        defaultTableModelHDCT = (DefaultTableModel) tbl_HDCT.getModel();
        defaultTableModelHDCT.setRowCount(0);
        for (HoaDonChiTiet hdct : listCT) {
            defaultTableModelHDCT.addRow(hdct.toDatata());

        }
    }

    public void showDataHoaDon() {
        System.out.println(listHD.get(tblHD.getSelectedRow()).getID());
        listCT = hdctService.showHDCT(listHD.get(tblHD.getSelectedRow()).getID());

        System.out.println(listHD.get(tblHD.getSelectedRow()).getID());
        defaultTableModelHDCT = (DefaultTableModel) tbl_HDCT.getModel();
        defaultTableModelHDCT.setRowCount(0);
        for (HoaDonChiTiet hdct : listCT) {
            defaultTableModelHDCT.addRow(hdct.toDatata());

        }
    }

    public void exportToExcel(List<HoaDon> hoaDonList, String filePath) {
        try (Workbook workbook = new XSSFWorkbook()) {
            Sheet sheet = workbook.createSheet("Hoa Don");

            // Tạo header row
            Row headerRow = sheet.createRow(0);
            String[] columns = {"Ma Hoa Don", "Ma NV", "Ma KH", "Ma Voucher", "Tong Tien", "Ngay Thanh Toan", "Trang Thai", "Mo Ta"};
            for (int i = 0; i < columns.length; i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(columns[i]);
            }

            // Điền dữ liệu vào các hàng
            int rowNum = 1;
            for (HoaDon hd : hoaDonList) {
                Row row = sheet.createRow(rowNum++);
                row.createCell(0).setCellValue(hd.getMaHoaDon());
                row.createCell(1).setCellValue(hd.getMaNV());
                row.createCell(2).setCellValue(hd.getMaKH());
                row.createCell(3).setCellValue(hd.getMaVc());
                row.createCell(4).setCellValue(hd.getTongTien());
                row.createCell(5).setCellValue(hd.getNgayThanhToan());
                row.createCell(6).setCellValue(hd.isTrangThai() ? "Có" : "Không");
                row.createCell(7).setCellValue(hd.getMoTa());
            }

            // Ghi file
            try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
                workbook.write(fileOut);
            }

            JOptionPane.showMessageDialog(null, "Xuất file Excel thành công!");

        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi xuất file Excel: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnXuatFile = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHD = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HDCT = new javax.swing.JTable();

        btnXuatFile.setText("xuất file");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        tblHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MaHoaDon", "MaNV", "MaKh", "MaVoucher", "TongTien", "Ngày Thanh toán", "Trạng Thái", "MoTa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHD);

        jLabel1.setText("Tìm Kiem");

        jButton1.setText("Tìm Kiếm theo maHD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl_HDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên Sp", "Mã HD", "Số Lượng", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_HDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HDCTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_HDCT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jButton1)
                            .addGap(52, 52, 52)
                            .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnXuatFile))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        // Lấy đường dẫn đến thư mục Desktop
        String userHome = System.getProperty("user.home");
        String desktopPath = userHome + File.separator + "Desktop";
        // Kết hợp với tên thư mục Desktop
        String filePath = desktopPath + File.separator + "hoa_don.xlsx"; // Đặt đường dẫn file bạn muốn lưu
        exportToExcel(listHD, filePath);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void tblHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHDMouseClicked
        int index = tblHD.getSelectedRow();
        //                fillForm1(listHD.get(index));
        showDataHoaDon();
    }//GEN-LAST:event_tblHDMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str = txttimkiem.getText();
        for (int i = 0; i < listHD.size(); i++) {
            if (str.equals(listHD.get(i).getMaHoaDon())) {
                tblHD.setRowSelectionInterval(i, i);
                showDataHoaDon();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_HDCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HDCTMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_HDCTMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblHD;
    private javax.swing.JTable tbl_HDCT;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
